### PR TITLE
Issue189 storage

### LINKED ISSUE #189: move EBC buffer storage into AixLib
This model needs some review regarding:
- [ ] structure
- [ ] MSL conformity
- [ ] documentation
- [ ] naming

We currently have a lot of dependencies to other models in EBC libs. We should check which models need to be moved as well, what their status is and if they can be replaced by AixLib or Annex60 models. If models need to be moved, we need to discuss where to put them in AixLib (in one `BaseClasses` package for `Buffer Storage` or into dedicated packages like `HeatTransfer`)

### PR DESCRIPTION
**Pull request by marcusfuchs**
Replacement for #290 to close #189.

### CODE REVIEW

**Comment by marcusfuchs** [comment]
@SebastianStinner 
This looks great! Still, before merging there are a few things we should address:

1. Model names are not according to style guide. E.g. `storage_wall` should be `StorageWall` and `HeatTransfer_lambda_eff` should be `HeatTransferLambdaEff`
1. Example `AixLib.Fluid.Storage.Examples.BufferStorage_Charging` (or better: `BufferStorageCharging`) should contain documentation that describes what to look for in results
1. New models should contain new entries in revision history for todays introduction to AixLib
1. `AixLib.Fluid.Storage.BufferStorage` documentation contains obsolete references to `HVAC` (also, image link is broken - this could be removed)
1. In `AixLib.Fluid.Storage.BufferStorage`, comment ` // Deleted: uebergabe von heatCond(lambda=lambda_water) an heat transfer` could be removed
1. There are many incorrect html tags

**Comment by marcusfuchs** [comment]
@SebastianStinner 
I fixed the html and added descriptions to parameters and components. I think we are near merge, but unfortunately there are still some minor issues:

1. In `AixLib.Fluid.Storage.BaseClasses.PartialHeatTransferLayers`, is it necessary to have have all the parameters defined as `final`?
1. In the heat transfer models, the heat flow rate is named `qFlow`. This may be hard to read for users, given the similiarity with `Q_flow`, which is also used in the model. Could we rename `qFlow` to something better?
1. Some heat transfer models use variables like `Real[n-1] k(unit="W/K")`. Could we use MSL types instead of `Real`?
1. `AixLib.Fluid.Storage.BaseClasses.HeatingCoil` uses the model `AixLib.Fluid.FixedResistances.Pipe`. In #134, we are aiming at removing this component. Can we change to e.g. a combination of Mixing Volume and `AixLib.Fluid.FixedResistances.FixedResistanceDpM` here?
1. In `AixLib.Fluid.Storage.BufferStorage`, there is the component definition `HeatTransfer heatTransfer "Heat transfer model"` as well as `replaceable model HeatTransfer`. Does this address the same and could it be combined?
1. `AixLib.Fluid.Storage.BufferStorage uses `BaseLib.Utilities.Round()`. This should be replaced or added to AixLib.

**Comment by SebastianStinner** [comment]
@marcusfuchs 
I fixed the issues with 1, 3, 4 and 6.

2. I think we should keep the name. I do not see another variable Q_flow (just an assertion of qFlow to a therm.Q_flow)

5. It definitely belongs together. But for the moment, we cannot delete one of them.

7. In the storage records in AixLib.DataBase.Storage, I could not find any "new" or "_".

**Comment by marcusfuchs** [comment]
Sorry if (7) was not clear, I was referring to e.g. `AixLib.DataBase.Storage.Generic_New_2000l` which could also be called `AixLib.DataBase.Storage.Generic2000l`. But we can maybe fix this in a separate issue. The model runs fine and I am happy to merge this. Great work!

**Pull request merged**
