### PR TITLE
Issue431 Changes in HOM

### PR DESCRIPTION
**Pull request by PMehrfeld**
see #431

### CODE REVIEW

**Comment by PMehrfeld** [comment]
@AnaConstantin: Thanks a lot. I'll take care of your points:


- [ ] Add in the documentation of all models which have a connection to the ground ... dependency of T_Ground from TRY. The source for this information is DIN EN 12831

- [ ] For the Example `OFDHeatLoad.mo` please split the set room temperature in convective and radiative. My suggestion would be to set the radiative to an adiabatic prescribed heat flow.

**Comment by PMehrfeld** [comment]
@AnaConstantin: Please have a look at my changes. Hopefully, I meet your requirements with these changes.

**Comment by AnaConstantin** [comment]
Thank you @PMehrfeld. I added the information on ground temperature for the ground floor model and the whole house model as well.
On my computer the OFDHeatLoad.mo does not simulate. It does simulate if I delete the explicit adiabatic condition for the start connectors of the rooms and just leave them unconnected. The heat flows are zero for the connectors (it's not as nice but it is handeled correctly). Please check this out.

- [ ] Make exmaple OFDHeatLoad.mo run

**Comment by PMehrfeld** [comment]
@AnaConstantin: Sorry, I have forgotten to change the class to `PrescribedHeatFlow`, so it was still `PrescribedTemperature`, which is of course nonsense as we want to create an adiabatic condition.

**Comment by AnaConstantin** [comment]
@PMehrfeld you are right, I didn't even notice that, as the names were correct. Great. I consider the branch is ready. You can merge whenever you want.

**Pull request merged**
