### PR TITLE
Added Plate Heat Exchanger Model, which is an updated version of the model developed by Thomas Dixius. (Marcus Lüdemann and Paul Thiele worked on this model)

### PR DESCRIPTION
**Pull request by tst-pth**
Updated Pull Request for the Plate Heat Exchanger

### CODE REVIEW

**Comment by marcusfuchs** [comment]
@tst-pth 
Thank you for the updated PR. This looks better, but still the `Utilities` sub-package is saved in one single file. Instead, it should be separate files for the package and each model.

**Comment by PMehrfeld** [comment]
Just a quick hint:
You can select (double click) the package `Utilities`, then click "Edit" at the top menu, then "Edit Attributes..." --> uncheck "Store as one file" --> "Directories - No Questions" --> "Save" (Ctrl + S)

**Comment by tst-pth** [comment]
@marcusfuchs @PMehrfeld 
Thank you very much for your help. I have updated my branch, I hope, it is now in the way it should be.

**Comment by thorade** [comment]
Here is how you can permanently uncheck that "Save in one file" checkbox.
http://www.modelon.com/blog/articles/dymola-tips-and-tricks-series-v-saving-packages-in-dymola/
http://stackoverflow.com/a/17399473/874701

**Comment by AnaConstantin** [comment]
This is a very helpful general hint, not just for this issue. Thanks a lot @thorade!

**Comment by PMehrfeld** [comment]
@tst-pth: Just as hint regarding changing the master to development: You can also use the edit button in the upper right corner and change the base branch into development. (Everyone can do this btw.)

**Comment by mlauster** [comment]
@tst-pth, are you still available and working on that PR or did you finish working at the institute in the meantime?

**Comment by pema1** [comment]
@mlauster I cloned @tst-pth's repo and merged development branch into it. Am now going through the models for name changes and other minor stuff. Will submit a pull request for RWTH-EBC:development later. If that does't work Paul needs to pull my changes and submit those.

**Comment by mlauster** [comment]
@pema1 thanks for picking that up! Please close this PR when you open a new one.

**Comment by pema1** [comment]
con:

- This model still has singularities which are not tested by examples at the moment (dT -> 0 and probably others)
- Coefficient of heat transfer (here: k) must be known in advance and provided as parameter. However, it is no parameter and dependent on m_flow, T and HX geometry.
- HX characteristic is for ideal counter flow which is a little optimistic.
- Pressure loss calculation is very simple (at least some good default values should be provided).

pro:

- Simple model with only a few equations.
- Very few parameters to fill in.

Remaining work:

[ ]  remove cP_DH and use cP_HS class for both media
[ ]  rename cP_HS to cpCalc
[ ]  rename Temperature_detection.mo into TempCalcOutflow.mo
[ ]  rename Inputs4toOutputs2.mo into HXcharacteristic.mo
[ ]  test singularities in Inputs4toOutputs2 by appropriate examples.
[ ]  add more documentation

I would be willing to make those changes if you are interested in this model. Note that I am currently working on VDI-Wärmeatlas model which is more complex but hopefully will solve some of the mentioned problems.

**Comment by tst-pth** [comment]
@pema1 and me will continue working on this topic in the next weeks in order to solve the problems mentioned in this pull request.

**Comment by mlauster** [comment]
@pema1, could you pick up that topic again and see if it is still of interest to merge these models?

**Comment by mlauster** [comment]
And we seems to have some unintended changes here, 290 files have been changed. I assume automatic white space changes by Dymola. They need to be reverted

**Comment by tstorek** [comment]
@pema1 @mlauster @marcusfuchs Unfortunately, @tst-pth left our institute today. Thus, he will not further work on the model. As far as I know the model has still some issues to be fixed before merging. How do we want to procede?

**Comment by mlauster** [comment]
Hm, that depends on how urgent that is for you @tstorek as supervisor. You either finish it yourself, assign a new student, find an interested assistant or close this PR for now. We should keep the issue in any case as well as the branch. Since the branch is currently at @tst-pth private account, you should create a new branch in AixLib and transfer the code into that branch (while keeping the history).

**Comment by PMehrfeld** [comment]
This PR will be aborted. Work continues in #486

**Pull request closed without merging**
