### PR TITLE
Issue64 update models - ready to merge

### PR DESCRIPTION
**Pull request by AnaConstantin**
Resolved conflicts and branch is not ready to merge in order to integrate AixLib in continuous usage at EBC.

### CODE REVIEW

**Comment by marcusfuchs** [comment]
Before merging, unit tests for LOM VDI Validation need to be fixed:
@mlauster : Commit https://github.com/RWTH-EBC/AixLib/commit/ef2fa3e95fdabd57c502a5fe2cd6ff05120ceaed renames the example files from TestCase_X to TestCaseX and strangely creates unit test scripts in the same folder. These should be deleted and instead the renaming has to be adjusted in AixLib/Resources/Scripts/Building/.../Validation/.../*.mos

**Comment by marcusfuchs** [comment]
Also, I fixed some package order files that were causing warnings with Dymola 2016. Please update to that version for testing before the merge.

**Comment by mlauster** [comment]
I updated the test cases and related unit test scripts.

**Comment by marcusfuchs** [comment]
Thanks, that works. I suggest merging this, then re-merging Annex 60, and start the bug-hunt afterwards.

**Pull request merged**
