### PR TITLE
Improved the model

### PR DESCRIPTION
**Pull request by AnaConstantin**
...see commit.
This should close issue #306

### CODE REVIEW

**Comment by mlauster** [comment]
@AnaConstantin, I assume you checked that it works as intended? For your next PR, it might speed up the process if you assign a reviewer. ;) Is somebody already working on that PR? If there are no comments until 29.11., I will merge that.

**Comment by AnaConstantin** [comment]
@mlauster, I just assigned @PMehrfeld for the pull.
A quick summary of what I did:
1. conditioned the existance of the Wind Speed Input of the choice of model for the calculation of the convective heat transfer
2. added an protected internal variable (type Real.Input) for the wind speed
3. added a connection between the input and the protected variable
4. added a dummy value for the protected variable when the input is not used
What I didn't do:
Created a type of the convection model to use instead of a Integer, because this parameter is referenced in the wall, room etc so we need at best a conversion script for that. And also a discussion on where to put such types. Another point to discuss is if parameters with custom types should have an Evaluate=true by default. After we discussed it together I can open a new issue and do something like this: types instead of integers and conversion scripts for the whole of AixLib.

**Comment by PMehrfeld** [comment]
From my point of view we can leave the Integers, since it is already documented in diverse models. Althoug I generally prefer enumeration types.
I think Evaluate should be set to true, where it makes sense.
Therefore, I suggest to add in the annotation of the definition of `Model` the command `Evaluate=true` so that 2 out of 3 if blocks will be removed during translation.
The changes of the commit look good!

**Comment by AnaConstantin** [comment]
Thought about it a bit more and I agree with @PMehrfeld that evaluate = true makes sense here.
Added it.

**Pull request merged**
