### PR TITLE
Issue309 pumps

### PR DESCRIPTION
**Pull request by TobiasBlacha**
this adds Pumps-package to the FastHVAC-package.

### CODE REVIEW

**Comment by mlauster** [comment]
@TobiasBlacha, please choose a reviewer.

**Comment by mlauster** [comment]
Hmm, looks like you have one equation too many in the set for generic outside couplings. I assume you don't get this error when `FluidSource` in a system model? Then it's a problem related to the outside couplings in the generic case. I don't have any direct suggestions, but yo might need to add some constraints or conditions to prevent the check from failing.

**Comment by mlauster** [comment]
Did you ever had a version without that error? It looks like your system is in fact overdetermined, related to the enthalpy port. You can calculate one of your values out of the others. So I wonder if this is a problem of the design of the port.

**Comment by TobiasBlacha** [comment]
If I still remember correctly, this error has something to do with the use of the enthalpy ports. The mass flow rate "m_flow" in the enthalpy port is defined as a flow variable, which leads to problems.

**Comment by mlauster** [comment]
@TobiasBlacha, there seem to be no further suggestions, I think we should discuss this PR in the Modelica group meeting and define how to proceed, e.g. if we ask for external help.

**Comment by SebastianStinner** [comment]
@mlauster @MichaMans @TobiasBlacha : We are currently redesigning the connector to prevent this error in the fluidSource. In system models, the fluidSource works, but as a single component, it is overdetermined because of the definition of m_flow as a flow variable.

**Comment by SebastianStinner** [comment]
@MichaMans : The requested changes are made. Could you review and merge this branch?

**Comment by MichaMans** [comment]
@SebastianStinner no more errors. Thanks for the improvement :smiley:

**Pull request merged**
