### PR TITLE
Issue406 new battery model

### PR DESCRIPTION
**Pull request by tst-pth**
This Pull Request refers to the issue #406 

It contains a model for a rack of batteries and a room, where these batteries can be installed. The model calculates the thermal performance of a room which contains different battery racks. The model needs an input which contains e.g. a vector of the battery loss.

It is possible that the names for the parameters and variables do not exactly correspond to the Modelica Guidelines, because I was not sure about the correct naming of some parameters. I hope that you can help me to fix this problem.

The solution with the temperature of the second battery is also not perfect for the moment. If you have any ideas to improve that, please let me know :)

### CODE REVIEW

**Comment by tst-pth** [comment]
I do not really know why the checks for the commits failed.. Can you maybe help me with that?

**Comment by mlauster** [comment]
It's quite easy: click on this little man and have a look in the log file. You have four models with html erros, here is the log, just for you, @tst-pth :)

unbenanntes bild

**Comment by tst-pth** [comment]
Ah thanks @mlauster! But I do not really understand the errors. I've now reduced the number of files with errors to 3 but it still doesn't work. And when I check the lines in my code which should be a problem I can not find anything wrong.

**Comment by mlauster** [comment]
Hm, it looks quite clear, you have two unexpected /ul, so they might not be opened. And two p's are wrong in your documentation. HTML errors are always related to documentation, or, even more often, to revisions section, which is directly next to the documentation

**Comment by tst-pth** [comment]
Ahh perfect thanks a lot, now it works :) Can I take you as reviewer @mlauster ?

**Comment by mlauster** [comment]
Hm, maybe you might start with a review of your supervisor, which is @tstorek if I get it correct. And something obvious from the number of changed files: You modified 180 files, what indicates that you incidentally included white space changes by Dymola when saving changes you made. You need to revert them, for what the best way is to checkout only the you really wanted to change in a new branch or simply reset all other files to the commit of development branch. Got that? :)

**Comment by mlauster** [comment]
replaced by #444

**Pull request closed without merging**
