### PR TITLE
Issue188 move chp

### LINKED ISSUE #186: move EBC boiler into AixLib
This model is already MSL conform and needs only minor revisions in documentation and naming. We need it for FastHVAC

### PR DESCRIPTION
**Pull request by PooyanJahangiri**
Closes #186 and #188

### CODE REVIEW

**Comment by mlauster** [comment]
@PooyanJahangiri, could you make a list of packages and at best files you intentionally changed? Then I could separate them from the unintentional ones.

**Comment by PooyanJahangiri** [comment]
@mlauster, here is the list of changes:

**New Packages**
- Fluid.HeatGenerators (and all its subpackages and models)
- DataBase.CHP (and all the data bases)
- DataBase.Boiler.General (and all the data bases)
- DataBase.Boiler.DayNightMode (and all the data bases)
- DataBase.Boiler.WorkLoad (and all the data bases)

**Deleted Models**
- Fluid.HeatExchangers.Boiler.mo
- Fluid.HeatExchangers.Utilities.BoilerEfficiency.mo
- Fluid.HeatExchangers.Utilities.HeatCurve.mo
- Fluid.HeatExchangers.Utilities.HeatDemand.mo
- Fluid.HeatExchangers.Examples.BoilerSystemTConst.mo
- Fluid.HeatExchangers.Examples.BoilerSystemTVar.mo

**Updated Models**
- Fluid.HeatExchangers.Examples.PumpRadiatorThermostaticValve.mo
- Fluid.HeatExchangers.Examples.PumpRadiatorValve.mo
- Fluid.HeatExchangers.Radiators.Examples.PumpRadiatorThermostaticValve.mo
- Fluid.HeatExchangers.Radiators.Examples.PumpRadiatorValve.mo
- Fluid.Storages.Examples.StorageBoiler.mo
- Building.HighOrder.Examples.Appartment_VoWo.mo
- Building.HighOrder.Examples.RoomGFOw2_DayNightMode.mo

**Comment by mlauster** [comment]
@PooyanJahangiri, could you check in merge295_revert if I caught all your intended changes or if something is missing/not intended?

**Comment by PooyanJahangiri** [comment]
@mlauster, all modifications are there, only the package orders are incomplete and I get the following warnings. I think the package.order files for the DataBase and Fluid should also be merged.

Warning: The package.order is incomplete, since the class DayNightMode in file/directory D:/Modelica/AixLib/AixLib/DataBase/Boiler/DayNightMode.mo is missing.

Warning: The package.order is incomplete, since the class General in file/directory D:/Modelica/AixLib/AixLib/DataBase/Boiler/General is missing.

Warning: The package.order is incomplete, since the class WorkLoad in file/directory D:/Modelica/AixLib/AixLib/DataBase/Boiler/WorkLoad is missing.

Warning: The package.order is incomplete, since the class CHP in file/directory D:/Modelica/AixLib/AixLib/DataBase/CHP is missing.

Warning: The package.order is incomplete, since the class HeatGenerators in file/directory D:/Modelica/AixLib/AixLib/Fluid/HeatGenerators is missing.

**Comment by mlauster** [comment]
Right, I missed that. Should be fixed now, can you cross-check? If everything is fine now, I would close this PR and open a new one for the fix-branch.

**Comment by PooyanJahangiri** [comment]
@mlauster, the warnings are gone and models are working. I also found an import command under Fluid.HeatGenerators.BaseClasses.Controllers.PITemp.mo which I removed now and pushed the change. I hope this doesn't affect all the other files.

**Comment by mlauster** [comment]
No, that worked fine. :) I will close this PR and open a new one.

**Pull request closed without merging**
