### PR TITLE
Plate Heat Exchanger (Issue274)

### PR DESCRIPTION
**Pull request by PMehrfeld**
This is related to issue #274 and PR #343. The old PR will be closed since its source was a student's fork.

I branched current AixLib development **and merged only the added files**!
As far as I understood the fork, no other models were changed. Only completely new components were added.

Maybe restructuring of packages is necessary.

### CODE REVIEW

**Comment by PMehrfeld** [comment]
Here is a list of 27 added files (sorted):

-----------------

AixLib/Building/BatteryModel/Battery_Rack.mo

AixLib/Building/BatteryModel/Battery_Room.mo

AixLib/Building/BatteryModel/ExampleBattery.mo

AixLib/Building/BatteryModel/package.mo

AixLib/Building/BatteryModel/package.order

-----------------

AixLib/DataBase/Batteries/BatteryRacks/Lead1_Rack74.mo

AixLib/DataBase/Batteries/BatteryRacks/Lead1_Rack78.mo

AixLib/DataBase/Batteries/BatteryRacks/RackBaseDataDefinition.mo

AixLib/DataBase/Batteries/BatteryRacks/package.mo

AixLib/DataBase/Batteries/BatteryRacks/package.order

AixLib/DataBase/Batteries/BatteryTypes/BatteryBaseDataDefinition.mo

AixLib/DataBase/Batteries/BatteryTypes/LeadBattery1.mo

AixLib/DataBase/Batteries/BatteryTypes/package.mo

AixLib/DataBase/Batteries/BatteryTypes/package.order

AixLib/DataBase/Batteries/package.mo

AixLib/DataBase/Batteries/package.order

-----------------

AixLib/Fluid/HeatExchangers/Examples/PlateHeatExchanger.mo

AixLib/Fluid/HeatExchangers/Examples/PlateHeatExchanger2.mo

AixLib/Fluid/HeatExchangers/Examples/cpCalc.mo

AixLib/Fluid/HeatExchangers/PlateHeatExchanger.mo

AixLib/Fluid/HeatExchangers/Utilities/Heat_Transfer.mo

AixLib/Fluid/HeatExchangers/Utilities/cP_DH.mo

AixLib/Fluid/HeatExchangers/Utilities/cP_HS.mo

AixLib/Fluid/HeatExchangers/Utilities/cpCalc.mo

AixLib/Fluid/HeatExchangers/Utilities/package.mo

AixLib/Fluid/HeatExchangers/Utilities/package.order

-----------------

AixLib/Resources/Scripts/Dymola/Fluid/HeatExchangers/PlateHeatExchanger/PlateHeatExchangerSimpleTest.mos

**Comment by mlauster** [comment]
@tstorek, this needs your attention. Please review and solve test issues

**Comment by mlauster** [comment]
@PMehrfeld, since you worked on that branch, can you take care of the test issues?

**Comment by PMehrfeld** [comment]
@mlauster: Sorry for my late reply. Actually, I am not aware of the content and aim of this PR and related issues. I think this should still be handled by @tstorek.
I only helped with repairing a student's fork. 

@tstorek : Can you maybe give us a targeted date for this PR and set a suitable milestone.

**Comment by DaJansenGit** [comment]
@tstorek @cvering Do we have some progress here? ;)

**Comment by DaJansenGit** [comment]
@tstorek As there seems to be no activity in here I will close this PR for now. Of course it can be reopened at  any time!

**Pull request closed without merging**
