### PR TITLE
Issue40 furthervalidation

### PR DESCRIPTION
**Pull request by mlauster**
Steffen left and validation will not be in foucs for next time. Resulst improved, so we should take this into the master.

### CODE REVIEW

**Comment by marcusfuchs** [comment]
I suggest that this should not be merged yet. Could you talk this through with @PRemmen and his work on the same models for #79? Furthermore, I have started to add unit tests for the linear validation in the branch for #79, which will be affected by the renaming of the test cases. Which should be merged first, this or #80 ?

**Comment by mlauster** [comment]
You are right, I just wanted to propose this branch for merging, but still some work is necessary. Let's start with merging #79 / #80 and let's do #82 afterwards

**Comment by marcusfuchs** [comment]
#80 is merged, so this is free to continue. When preparing this branch for a merge, please also take the unit tests into account.

**Comment by mlauster** [comment]
I set up a new request as this one is not helpful to merge

**Pull request closed without merging**
