### PR TITLE
Issue467 compressors

### PR DESCRIPTION
**Pull request by MirkoEngelpracht**
Hello everyone,

this issue should have been solved now and can be reviewed. I assume that I'll need to change a few things as soon as the refrigerant library developed at #408 is merged into the development branch because the compressor models have been developed with respect to the new refrigerant media model. However, it may be reasonable to request a first review.

### CODE REVIEW

**Comment by tstorek** [comment]
Hi Mirko,
Thank you very much! Did you really change 176 ? This looks a little too much;) Please, doublecheck how you safed the changes. Did you make changes in the package.order? This has usually big influence on the whole library.

Cheers,

Thomas

**Comment by MirkoEngelpracht** [comment]
**Changes**

I've corrected some smaller mistakes:

- Added graphical connections and library icons
- Moved sensor model into sensor package
- Removed parameters tthat are not needed of the model 'PartialModularPort_ab'
- Simplified the whole library while changing the way of saving the efficiency models

@tstorek: I've reduced the amount of files. Concerning your questions about the package.order: I've changed it. However, as far as I understand that will automatically happen if you add a new package etc. into the library. Please correct me, if I am wrong here!

**Open Issues**

As @PMehrfeld told @cvering, I still need to introduce the annotation 'ConnectorPortSizing=true' to avoid unnecassary workarounds.

Moreover, I still have a numerical jacobian and need to remove it but don't know how to do it. I get the following warnings while translation and activating the flag 'hidden.printfailuretodifferentiate=true':

grafik

Does anybody know a solution or could help me by telling me how I proceed further?

**Comment by mlauster** [comment]
@cvering, how to proceed with that?

**Comment by DaJansenGit** [comment]
@cvering @tstorek @MirkoEngelpracht Anything new?

**Comment by PMehrfeld** [comment]
@cvering: I deleted the branch. Please restore it, if you need it for further development.

**Pull request merged**
