### PR TITLE
PV System connectable with new weather model

### PR DESCRIPTION
**Pull request by larissakuehn**
This pull request refers to issue #460.

I added a second PV System to the library, which contains a weather bus instead of a solar radiation connector. 
In order to get the amount of the radiation on a tiled surface I added AixLib.BoundaryConditions.SolarIrradiation.DiffusePerez" and "AixLib.BoundaryConditions.SolarIrradiation.DirectTiltedSurface" to the model. 

In addition to that I createt a small example equal to the example of the existing PVSystem.

### CODE REVIEW

**Comment by TobiasBlacha** [comment]
@larissakuehn the new models still have to be inserted into the packageorder, i will do this now.

**Comment by PMehrfeld** [comment]
@larissakuehn: Thanks a lot for you modelling work.
Instead of just duplicating the models, we prefer the approach of extending partial models.
These two PVSystem models are an ideal example for this. You should create a partial BaseClass for the identical parts that `PVSystem(TMY3)` use as well as for `PVModuleDC(_TMY3)`. 

By the way: Please remove the underscore (_) in the BaseClass model.

If you are not so familiar with extending from base classes, have a look at models that make use of this functionality; ask your supervisor; or ask me (I suggest to stick to this order ;) )

**Comment by PMehrfeld** [comment]
Ah and regarding your question about where to merge your branch:
Normally, I would say it is sufficient to merge the branch into the branch `issue309_fastHvac`. But just in case `issue309_fastHvac` is not going to be merged into `development` ever, we should go with:

1. from `issue460_PVSystem` into `development` (which is exactly this PR)
1. merge `development` into `issue309_fastHvac`

**Comment by larissakuehn** [comment]
@PMehrfeld and @TobiasBlacha  Thank you for all your advices!!
I have changed it now, hopefully correctly.

**Comment by TobiasBlacha** [comment]
@PMehrfeld `issue309_fastHvac` will not be transferred completely into `development` at once, because it is to much work for a review. We want to transfer `issue309_fastHvac` step by step, so I would also proceed as you suggested.

**Comment by TobiasBlacha** [comment]
@larissakuehn the example for the new pv model `ExamplePVTMY3` can not be executed because the path to the weather file has to be changed.
And i have tested the old pv model, the orientation of the pv pannel is not taken into account. 
In order to get the amount of the radiation on a tiled surface we should add
`AixLib.BoundaryConditions.SolarIrradiation.DiffusePerez` and `AixLib.BoundaryConditions.SolarIrradiation.DirectTiltedSurface` too, or what do you think @larissakuehn ?

**Comment by PMehrfeld** [comment]
@TobiasBlacha: If I get you correctly, the orientation comes with the connection from the weather model. It depends which connection `Weather.SolarRadiation_OrientedSurfaces[1..6]` you use.

**Comment by TobiasBlacha** [comment]
@PMehrfeld in the pv model the orientation of the pv pennels can be selected as parameters (Location, Geometry), which suggests that the orientation can be adjusted here.  But changes of these parameters have no effects, since you have already said that the orientation is given by the connections.


unbenannt

**Comment by larissakuehn** [comment]
@TobiasBlacha: I will change the path to the weather file.

I had a look at the old PV Model, which is in the development branch. There the PV model has no parameters for lat, til and azi. I added them to the PartialPVSystem model by mistake. 
I will compare both models again and correct it.
So I think in the old model these parameters are set within the weather data?

**Comment by PMehrfeld** [comment]
Ah, of course, you are absolutely right! (So I really understood you wrong.)

@larissakuehn: Very good with extending the models.
But I still have one more suggestion to improve the `PVSystem` model and get rid of two models.
Since `PVModuleDC` and `PVModuleDCTMY3` only distinguish in the irradiation variable, you can delete both models but insert the RealInput and the equations to `PartialPVModuleDC` and remove the prefix "Partial" (in the name and before "model"). Afterwards revise the model `PVSystem` like in the screenshot by inserting the model `Modelica.Blocks.Sources.RealExpression` with `k = IcTotalRad.I`.


grafik

Furthermore a few more points:

- [ ] Do you have literature sources for the equations. If so, please mention them in the information section.

- [ ] Add your name and a date to the revision section, where necessary

- [ ] `pVmoduleDC1` is not a good component name. Generally, it is correct to start with lowercase for component names. But for readability, "PVModuleDC" would be the correct name (uppercase "M" and "P" and remove 1). The same with `pVinverterRMS` --> "PVInverterRMS".

- [ ] After revising the model check the information section again for correctness.


One last thing: The whole models are not correct from the point of view of the [naming conventions](https://github.com/RWTH-EBC/AixLib/wiki/Namespaces). But we should not solve this in this issue as changes in renaming paramters need conversion scripts.

**Comment by PMehrfeld** [comment]
> So I think in the old model these parameters are set within the weather data?

Exactly! The information of tilt is not relevant since ange of inclination is transported through the solar radiation connector.

**Comment by mlauster** [comment]
@PMehrfeld and @TobiasBlacha, as you were giving a lot of feedback and already picked up reviewing, I unassigned myself and will leave the review to you.
@larissakuehn, you still have some html issues, you see analyse them at

https://travis-ci.org/RWTH-EBC/AixLib/builds/290420136?utm_source=github_status&utm_medium=notification

**Comment by PMehrfeld** [comment]
@larissakuehn and @TobiasBlacha: Can I merge?

**Comment by TobiasBlacha** [comment]
@PMehrfeld I will check the last changes tomorrow, then we can merge.

**Comment by larissakuehn** [comment]
@TobiasBlacha and @PMehrfeld:
Thank you for all your help!

**Comment by TobiasBlacha** [comment]
@PMehrfeld and @larissakuehn The links to the manufacturers datasheets in the documentation of `PVSystem` and `PVSystemTMY3` are not available, but I would open a new issue for it. I think we can merge it.

**Comment by TobiasBlacha** [comment]
@larissakuehn I do not know if you are still working with the branch ìssue460_PVSystem`. If not, the branch can be deleted.

**Comment by larissakuehn** [comment]
@TobiasBlacha No, I am not working with the branch anymore.
But should I really merge (respectively create a merge request) the development branch into the branch issue309_fastHvac or can I also merge the branch issue460_PVSystem to the fastHvac branch?

**Comment by TobiasBlacha** [comment]
@larissakuehn because we allready merged the development branch into issue460_PVSystem branch it makes no difference. But I think you'll have some merge conflicts  if you want to merge the whole development branch. Maybe it is an option to add just the PV Model to the issue309_fastHvac branch?

**Comment by larissakuehn** [comment]
@TobiasBlacha: Ok, that sounds good for me, I will add it tomorrow.

**Pull request merged**
