### PR TITLE
Solved issue232 hydraulic resistance

### PR DESCRIPTION
**Pull request by pema1**
* Modified flow equation to take care of flow direction. 
* Also reformulated formula to avoid exponential notation. 
* Added a test case and graphic to show old and new behavior.
* Added two test cases to compare simulation speed of FixedResistancesDpM and HydraulicResistance (with graphics).

### CODE REVIEW

**Comment by marcusfuchs** [comment]
@pema1 Thanks for your improvements of the model!

Before merging, I have a few remarks:
- I fixed a typo in the example names
- According to the Modelica Guidelines (see e.g. https://github.com/RWTH-EBC/AixLib/wiki/Namespaces#model-block-and-package-names) the example names should not contain `_` but use camel case. Can we rename `AixLib.Fluid.FixedResistances.Examples.Compare_FixedResistances_HydraulicResistance` to e.g. `AixLib.Fluid.FixedResistances.Examples.CompareFixedResistances` ?
- The examples `AixLib.Fluid.FixedResistances.Examples.Compare_FixedResistances_HydraulicResistance1` and `AixLib.Fluid.FixedResistances.Examples.Compare_FixedResistances_HydraulicResistance1` do not really compare the two models within themselves. Can we rename those to e.g. `AixLib.Fluid.FixedResistances.Examples.PreformanceHydraulicResistance` ?
- The examples do not contain any documentation. Could you write a short description so that others can quickly see what the examples are illustrating?
- You pushed 3 image files. Are these used anywhere? If so, could you please move those to `AixLib\AixLib\Resources\Images`?
- The assert-statement in `AixLib.Fluid.FixedResistances.Examples.Compare_FixedResistances_HydraulicResistance` line 49 raises the message `"Inputs differ, check that lossless pipe is correctly implemented."` - should we change that message, as no lossless pipe is used in the model?

**Comment by pema1** [comment]
Hello Marcus,

- Will change the names.
- Will add some documentation.
- The examples and images were thought of as an intermediate documentation that could be removed again. However, if you want to keep it that is fine with me. The images will probably only be used, if ever, in the example models for illustration. I will have a look.
- The long simulation was used to assess the perfomance of the models. The idea is to have a reasonably long simulation time as to average out possible speed fluctuations during simulation. I think we can reduce the simulation time and make a note to the user in the documentation.

**Comment by pema1** [comment]
@marcusfuchs I pushed the changes you requested. Could you review? 
My problem with the commit was 2-factor-authentication comming in my way while trying to push. Therefore the authentication failure.

**Comment by marcusfuchs** [comment]
@pema1 
Everything looks great now, it only seems to me like the equations in the documentation of `AixLib.Fluid.FixedResistances.Examples.PerformanceHydraulicResistance2` are not displayed correctly. It seems like the folder `AixLib/Resources/Images/equations` has not been included in your commits. After fixing this I'll be happy to merge.

**Pull request merged**
