### PR TITLE
Issue354 Add controllers and controller interfaces

### PR DESCRIPTION
**Pull request by MBaranskiEBC**
I added the first controller and the corresponding interface. They can be used in combination with theHeatPumpDetailed.

### CODE REVIEW

**Comment by marcusfuchs** [comment]
@MBaranskiEBC As I am finished with my review for now, I will re-assign the issue back to you. When you think it is time for me to review again, please re-assign back to me.

**Comment by MBaranskiEBC** [comment]
@marcusfuchs thanks a lot for your comments. I think I have followed them all, so I'll re-assign you. The only thing is I have not created a subpackage "ComponentControllers", yet. We can discuss that, so far I have just removed the additional "Controller" from the subpackages I had created. Thanks again!

**Comment by marcusfuchs** [comment]
@MBaranskiEBC 
As discussed, my only open points would be the missing documentation strings and the variable names `realValue`, `realValue1`, and `booleanValue` in the example.

**Comment by marcusfuchs** [comment]
@MBaranskiEBC 
Perfect, thank you for this great contribution! 

Time from issue creation until merge: 34 days.

**Pull request merged**
