### PR TITLE
Issue333 hydraulic resistances

### PR DESCRIPTION
**Pull request by PMehrfeld**
- see #333 
- I deleted standard parametrization for zeta and diameter!
- I also changed the parameter naming for the diamter from `D` to `diameter` according to https://github.com/RWTH-EBC/AixLib/wiki/Variable-Naming
- Please use conversion script to change paremeter in your models: `convertElement("AixLib.Fluid.FixedResistances.HydraulicResistance","D","diameter")`
- I also recommend the conversion script for people who are still using our old HVAC library: `convertClass("HVAC.Components.HydraulicResistance.HydResistance", "AixLib.Fluid.FixedResistances.HydraulicResistance");`

### CODE REVIEW

**Comment by PMehrfeld** [comment]
This closes #333

**Comment by PMehrfeld** [comment]
Due to @pema1's comments in #333 we should wait with this pull request. @AnaConstantin please wait with the merge. Thanks @pema1 for the good annotations.

**Comment by PMehrfeld** [comment]
All changes are made. @AnaConstantin: You can start with the review.

**Comment by AnaConstantin** [comment]
@PMehrfeld thank you for the work done. Please excuse the long time it took me to do the review.
I only have three observations:
1. Please address in the documentation of HydraulicResistance what are the common points and the differences regarding modelling with the model PressureDrop
2. Please address in the documentation of Examples.CompareFixedResistances the fact that the parameters of the HR-component are set in order to have the same behaviour as the FRdp component.  At first glance they are quite intriguing.
3. In the Icon of the HydraulicResistance make the text bigger, so at least in the example you can see the value of Examples.CompareFixedResistances. I suggest to change the number to a real value, instead of a ratio in the Example.

**Comment by PMehrfeld** [comment]
@AnaConstantin: Thanks for your comments. I changed what you have requested besides the denominator 8 in the parameter `HR.zeta`, since this number is used to calculate `dp_nominal`. I explain this in the example's documentation.

If you have no further comments, you can merge this branch. Thanks again!

**Pull request merged**
