### PR TITLE
Merge ibpsa for release0.6.0

### PR DESCRIPTION
**Pull request by PMehrfeld**
Merge of `IBPSA` library into development in order to prepare the release v0.6.0

### CODE REVIEW

**Comment by PMehrfeld** [comment]
- [ ] Check for WhiteSpace issues due to Dymola

- [ ] Correct errors in `AixLib.Controls.HVACAgentBasedControl`

**Comment by mlauster** [comment]
I volunteer as reviewer :wink:

**Comment by PMehrfeld** [comment]
@mlauster:  Thanks for your offer. I'll assign you as soon as I have solved the issues mentioned above ;)

**Comment by PMehrfeld** [comment]
@mlauster : Feel free to do the review :)

**Comment by PMehrfeld** [comment]
There is only one minor issue regarding FastHVAC, which will be solved [here](https://github.com/RWTH-EBC/AixLib/issues/337#issuecomment-411085033). However, this should not stop us from merging and releasing this branch.

**Comment by PMehrfeld** [comment]
Thanks a lot @mlauster. I compare checks in Dymola for each top-level package between latest development and this branch. I solved a few errors and only left the problem with FastHVAC I addressed above. Anyway, this is a check error that does not occur when using the models with an appropriate parametrization. And this will be solved in #337 anyway.

**Pull request merged**
