### PR TITLE
Fix minor type issues

### LINKED ISSUE #329: Minor issues in AixLibSocketCommunication.h
1. It says `unsigned char **convertDbltoHex(double num)` in AixLibSocketCommunication.h, but return value is of type `unsigned char *`.
1. It says `int SocketReceive(char **buffer, int maxLen, int socketHandle)` in AixLibSocketCommunication.h but according to the MLS it should be `const char **buffer`.

### PR DESCRIPTION
**Pull request by tbeu**
Close #329

### CODE REVIEW

**Comment by mlauster** [comment]
This PR points to the master, I think it could be placed in the development

**Comment by AnaConstantin** [comment]
Thank you @ for your input. I agree with the cahnges. Could you please as @mlauster suggested create a pull request that points to the development branch, as maily bugs are to be directly mearged in the master? Once this is done, I'll accept the pull request.
Thank you very much!

**Comment by mlauster** [comment]
just to fix @AnaConstantin remarks: Thank you @tbeu for your input. I agree with the changes. Could you please as @mlauster suggested create a pull request that points to the development branch, as only bugs are to be directly merged in the master? Once this is done, I'll accept the pull request.
Thank you very much!

**Comment by tbeu** [comment]
Superseded by #349.

**Pull request closed without merging**
