### PR TITLE
solar thermal collector

### PR DESCRIPTION
**Pull request by PMehrfeld**
Related to #293.

1. I identified to PartialHeatGeneration models. I extended the `SolarThermal` from `AixLib.Fluid.BoilerCHP.BaseClasses.PartialHeatGenerator` and deleted `AixLib.Fluid.HeatExchangers.BaseClasses.PartialHeatGen` since the other one is already correctly paramtrized according to the IPBSA conventions.
1. Efficiency is now calulated based on the mean temperature of the collector.
1. Also `eta_zero` is used as upper limit for `eta`.
1. Minor improvements, e.g. regarding units.

I did not change parameter and variable names to meet the naming conventions. Otherwise conversion scripts would be necessary.

Furthermore, the `PartialHeatGenerator` model is not only used in the `BoilerCHP` subpackge. Maybe it should be moved some day.

Since @KFinkbeiner still wants to compare our solar collector to other existing ones, issue #293 can stay open.

But this branch can be deleted after a successful merge.

### CODE REVIEW

**Comment by mlauster** [comment]
@pema1, you are assigned as reviewer. Can you please review?

**Comment by pema1** [comment]
@mlauster or @PMehrfeld can you make sense of the errors in those two checks?  I can run the model in Dymola without a problem.

**Comment by mlauster** [comment]
@pema1, we test only html validity of documentation and revision section. This ensures that you can open AixLib with OpenModelica since Dymola often writes and accepts malformed html code.
You can view the details when clicking on the red cross (you will be forwarded to the log console of Travis CI). Here is a snapshot:

unbenanntes bild

**Comment by mlauster** [comment]
@pema1, by the way, you still need to make your review. You can start a review when clicking on "files changed" and then on "start review".

**Comment by PMehrfeld** [comment]
@mlauster: Thanks for clarifying the HTML errors. I should have waited for the finished CI checks.
@pema1: Thanks a lot for the pedantic code review and for directly committing your changes. 

I think using `Modelica.Constants.eps` in this context should work fine. But thank you for the hint. To be honest, I was not aware of `Modelica.Constants.small`. 

As long as no one directly access the `gain` block in the model, a `convertElement()` is not necessary. So, it's OK to not have this conversion in the script.

**Pull request merged**
