### PR TITLE
Issue309 fast hvac

### PR DESCRIPTION
**Pull request by jeremylinquanyi**

### CODE REVIEW

**Comment by PMehrfeld** [comment]
Be careful, this is a pull request for merging into master. Is this correct @TobiasBlacha ?
Otherwise base branch should be changed to development.

**Comment by TobiasBlacha** [comment]
@jeremylinquanyi what is the background or the reason for your pull request? We have just begun to work on integrating of the Fast HVAC library into the AixLib.

**Comment by jeremylinquanyi** [comment]
@TobiasBlacha  I am so sorry, i have misclicked.

**Comment by TobiasBlacha** [comment]
@jeremylinquanyi okay, no problem. Then i will close this pull request.

**Pull request closed without merging**
