### PR TITLE
Fix socket communication

### LINKED ISSUE #277: Communications to use Modelica_DeviceDrivers
As mentioned in #149, the communication package should use [https://github.com/modelica/Modelica_DeviceDrivers](https://github.com/modelica/Modelica_DeviceDrivers).

### PR DESCRIPTION
**Pull request by tbeu**
Utilize TCP/IP socket communication from Modelica_DeviceDrivers.

TODO: 
* Possibly remove AixLibSocketCommunication.h
* Cleanup obsolete functions

Close #277

### CODE REVIEW

**Comment by mlauster** [comment]
@tbeu, thanks a lot for taking over this issue! We really appreciate your efforts and again sorry for having such a delay in this issue. @AnaConstantin agreed to take over the review, if the little ones keep her busy, I will take over this duty.

**Comment by AnaConstantin** [comment]
@tbeu thank your for taking the time to do this. To me it looks very interesting. I'll go through it by the beginning of next week (10.09).

**Comment by AnaConstantin** [comment]
@tbeu sorry for answering so late. Would you please redo the pull request, to merge into the issue277_comDeviceDrivers branch? Our work flow is to first merge the branch into the development and then into the master.

**Comment by PMehrfeld** [comment]
@AnaConstantin: I changed the base (target) branch to `development`. Hope that is what meant :)

**Comment by AnaConstantin** [comment]
@PMehrfeld thank you! Realised I can do this myself. Learned something new! I think I'll first merge into the branch and then do the suggested deletions, change the documentation to correctly reference the DeviceDrivers library and then do a pull request for development.

**Comment by tbeu** [comment]
OK from my side. Yes doc and superfluous files should be adapted.

**Comment by AnaConstantin** [comment]
@tbeu thank you for your answer. I plan to deal with this issue fast. I will mention you in any comment regarding it, as it would be great if you can look over the changes I made or if I have any questions. I will use the comments section of the issue and assign the issue to you too if that is ok. I think in this way you are still in the loop.

**Pull request merged**
