### PR TITLE
move AHU from HVAC to Airflow. also documentaion change in AHU info.

### PR DESCRIPTION
**Pull request by PMehrfeld**
#177

### CODE REVIEW

**Comment by marcusfuchs** [comment]
To check if everything is working, I tried to simulate `AixLib.Building.LowOrder.Examples.MultizoneExample`, but simulation fails (see below). Does it work for you @PMehrfeld ?

> Integration started at T = 0 using integration method DASSL
> (DAE multi-step solver (dassl/dasslrt of Petzold modified by Dynasim))
> ERROR: Failed to solve non-linear system using Newton solver.
> To get more information: Turn on Simulation/Setup/Debug/Nonlinear solver diagnostics/Details
> Solution to systems of equations not found at time = 1.27421E+006
>    Nonlinear system of equations number = 3
>    Infinity-norm of residue = 1.03812E+032
>    Number of calls to nonlinear solver DymNL has reached or exceeded
>    the maximum allowed number of function calls= 800
>    Accumulated number of residue       calc.: 669127
>    Accumulated number of symbolic Jacobian calc.: 201617
>    Last values of solution vector:
> multizoneEquipped.zone[3].machines_SensibleHeat_DIN18599.RadiativeHeat.port.T = 78.4315
> multizoneEquipped.zone[3].lights.RadiativeHeat.port.T = 317.19
> multizoneEquipped.zone[3].buildingPhysics.reducedOrderModel.outerwall.port_b.T = 281.991
> multizoneEquipped.zone[3].buildingPhysics.reducedOrderModel.heatConvInnerwall.port_b.T = 275.713
> multizoneEquipped.zone[3].internalGainsRad.T = 6.04011
> multizoneEquipped.zone[3].buildingPhysics.reducedOrderModel.solarRadToHeatRad.port.T = -14.7313
> multizoneEquipped.zone[3].human_SensibleHeat_VDI2078.RadiationConvertor.Therm.T = -4.77283E+009
>    Last values of residual vector:
> { 7.7886E-005, 0.000200392, -5.1906E+031, 0.595532, -5.1906E+031,
>   -1.10741, -0.00329553 }
>  
> Integration terminated before reaching "StopTime" at T = 1.27e+006
>    CPU-time for integration      : 11.9 seconds
>    CPU-time for one GRID interval: 33.5 milli-seconds
>    Number of result points       : 1915
>    Number of GRID   points       : 355
>    Number of (successful) steps  : 24243
>    Number of F-evaluations       : 92631
>    Number of H-evaluations       : 27004
>    Number of Jacobian-evaluations: 9175
>    Number of (model) time events : 707
>    Number of (U) time events     : 0
>    Number of state    events     : 250
>    Number of step     events     : 0
>    Minimum integration stepsize  : 0.0072
>    Maximum integration stepsize  : 893
>    Maximum integration order     : 5
>

**Comment by PMehrfeld** [comment]
I do not receive an error... I have simulated with Dymola 2016 FD01, 32 bit / 64 bit, Visual Studio 2013, with and without parallelization. Maybe you can specify your settings / used software.
Anyway, the error message does not look totally unfamiliar to me. But I am pretty sure it has to do with the zone parametrization and not with the AHU model directliy.

**Comment by marcusfuchs** [comment]
I can confirm that the model runs with Dymola 2016 FD01. This is not ideal, but as this is also probably not caused by the current changes but a fundamental problem, I will merge this after fixing a few html errors.

**Comment by marcusfuchs** [comment]
I fixed the html, but I have two more concerns:

- In the `graphics` annotation, there are very long strings for the `image_source`. I think these should be removed
- The diagram view does not seem to be right. Can we extend the diagram size to fit all components?

**Comment by PMehrfeld** [comment]
- The images had been stored within the model file. Now I have added the images in the appropriate folder and linked to them relatively.

- I have adjusted the boundaries independently in the Icon view and the Diagram view. In the Icon view it makes sense to have the boundaries adapted to the image of the AHU schema.

**Pull request merged**
