### PR TITLE
WIP: B13 integration ideal heater threshold

### PR DESCRIPTION
**Pull request by DaJansenGit**
Integration of a outside temperature based control for the IdealHeaterCooler.
This should prevent ideal heating during summer, when the AHU cooling lowers the temperature below set temperature for a short period of time or vice versa in winter.

### CODE REVIEW

**Comment by DaJansenGit** [comment]
Some changes in teaser output are required to make this work out of the box.

**Comment by DaJansenGit** [comment]
Since @PRemmen ist changing the filesystem from the use conditions to json in #584, I will wait for the integration and integrate the default values into the use conditions.

**Comment by DaJansenGit** [comment]
closed due to #823

**Comment by PRemmen** [comment]
@DaJansenGit I also commented in TEASER, it seams that there is something wrong with the threshold variable :) https://github.com/RWTH-EBC/TEASER/issues/617

**Pull request closed without merging**
