### PR TITLE
[WIP] #403 added a NoReturn supply model with pump and temperature set

### PR DESCRIPTION
**Pull request by MichaMans**
This adds a NoReturn supply model with the possibility to set flow temperatures through an input and it works with a pump model.
@marcusfuchs could you have a quick look at it? Whats your suggestion do we need this? can we use this?

Things to do before merge:

- [ ] HTML Errors Revision

- [ ] Adding a few comments and maybe tests

### CODE REVIEW

**Comment by marcusfuchs** [comment]
@MichaMans Thanks for sharing this! I think the addition will help us for the next steps. I'm just wondering whether we could have a model with the shown functionalities and the ideal source both sharing a common base class?

**Comment by MichaMans** [comment]
I think that's a good idea. Then we start by making a NoReturn base class and then extend from there to ideal Source and idealSourcePump. Any naming suggestions?

**Comment by marcusfuchs** [comment]
How about https://github.com/RWTH-EBC/AixLib/blob/issue403_dhc/AixLib/Fluid/DistrictHeatingCooling/BaseClasses/Supplies/NoReturn/PartialSupply.mo ? ;)

We can of course change the existing model, but at least we already have one.

**Comment by MichaMans** [comment]
Ha! Missed that! Good point! Trying to start this asap

**Comment by MichaMans** [comment]
At the moment we are not passing the html checks. According to Travis its the HydraulicValidation file. In addition i get some warnings while opening the AixLib.  @marcusfuchs do you get any warnings about missing mo files in package.orders too?

**Comment by marcusfuchs** [comment]
@MichaMans I think the warnings are fixed in `development`. I'll update your branch. 

Regarding the `HydraulicValidation`: I think we will not need this in the future, as we can instead use the network from `AixLib.Fluid.FixedResistances.Validation.PlugFlowPipes.PlugFlowAIT` as a simple reference case. I'll check whether we can delete `HydraulicValidation`.

**Comment by marcusfuchs** [comment]
I did some renaming and added units to the inputs and outputs. So far, I did not change anything on the pressure input `p_NSP`. I was not sure whether this should be the supply pressure at the network's weakest point or rather the `dp` between the weakest points supply and return pressures? And should we pack the PID into a pressure controller similar to the temperature controller? Then we could also have a version that just propagates a `dp` to the pump, which may be useful in the future.

In addition, I'll see whether I can add an example for the ideal source with prescribed temperature.

**Comment by marcusfuchs** [comment]
As discussed today I'll close this and merge branch `issue403_supplyIn` instead.

**Pull request closed without merging**
