### PR TITLE
Issue462 modular hydraulic systems

### PR DESCRIPTION
**Pull request by alexanderAKU**
> Thank you for making a Pull Request to AixLib!

> Please consider these points before submitting:
> - Mention the issue that this Pull Request intends to solve, and briefly describe what the main changes are.
> - Make sure all new code follows our [Modelica Guidelines](https://github.com/RWTH-EBC/AixLib/wiki/Modelica-guidelines)
> - Make sure all new models include documentation as described in the [Documentation Wiki-Page](https://github.com/RWTH-EBC/AixLib/wiki/Documentation) and are demonstrated by suitable examples

> If you know someone who could review your code, please use the *Reviewer* function on the right to ask for a review and also assign the PR to them. If not, no worries, we will find someone for you.

> Thanks again for your PR! You can delete these first lines before submitting your PR.

### CODE REVIEW

**Comment by PMehrfeld** [comment]
This is the essential list of added models. The remaining changed files are not important.

AixLib/Controls/HydraulicModules/CtrAdmix.mo
AixLib/Controls/HydraulicModules/CtrUnmixed.mo

AixLib/Fluid/HydraulicModules/Admix.mo

AixLib/Fluid/HydraulicModules/BaseClasses/BasicPumpInterface.mo
AixLib/Fluid/HydraulicModules/BaseClasses/HydraulicBus.mo
AixLib/Fluid/HydraulicModules/BaseClasses/PumpBus.mo
AixLib/Fluid/HydraulicModules/BaseClasses/PumpInterface_SpeedControlledNrpm.mo

AixLib/Fluid/HydraulicModules/Example/Admix.mo
AixLib/Fluid/HydraulicModules/Example/ERC_ExperimentalHall_CoolingCircuit.mo
AixLib/Fluid/HydraulicModules/Example/Injection.mo
AixLib/Fluid/HydraulicModules/Example/Throttle.mo
AixLib/Fluid/HydraulicModules/Example/ThrottlePump.mo
AixLib/Fluid/HydraulicModules/Example/Unmixed.mo

AixLib/Fluid/HydraulicModules/Injection.mo
AixLib/Fluid/HydraulicModules/SimpleConsumer.mo
AixLib/Fluid/HydraulicModules/Throttle.mo
AixLib/Fluid/HydraulicModules/ThrottlePump.mo
AixLib/Fluid/HydraulicModules/Unmixed.mo

**Comment by PMehrfeld** [comment]
I found some issues @alexanderAKU :

- [ ] Use the prefix `final` when passing through parameters. Also use the statement with redeclaring a medium package like [here](https://github.com/RWTH-EBC/AixLib/blob/issue462_ModularHydraulicSystems/AixLib/Fluid/HydraulicModules/Admix.mo#L42).

- [ ] When checking the examples I receive an "incompatible units" warning. Please solve this.

- [ ] There are strange circles in the Hydraulic Modules (see screenshot below).

image

**Comment by alexanderAKU** [comment]
@PMehrfeld I have reworked the models now. Please have a look on it. Maybe we could combine the merge with the new issue #581 .

**Comment by mlauster** [comment]
@PMehrfeld, any plans to review this and add it to the next release?

**Comment by PMehrfeld** [comment]
@mlauster : yes, I am going to review this tomorrow. But the plan is to release v0.6.0 prior and include this project in v0.7.0.

**Comment by PMehrfeld** [comment]
@alexanderAKU : We are almost done. I changed a few more things. Mainly I added energyDynamics to the modules in order to avoid warnings regarding under determined initialization. Furthermore, I propagated PID parameters of `AixLib.Systems.HydraulicModules.Controller.CtrAdmix` for a stable init of `ERC_ExperimentalHall_CoolingCircuit`

But I still have two more points:

- [ ] It is probably possible to extend `AixLib.Fluid.Interfaces.PartialTwoPortInterface` in the partial model `AixLib.Systems.HydraulicModules.BaseClasses.BasicPumpInterface`.

- [ ] In `AixLib.Systems.HydraulicModules.Example.Injection` still the outer component `system` is missing. Maybe the point above solves this problem.

**Comment by alexanderAKU** [comment]
@PMehrfeld I added the points above.

**Comment by alexanderAKU** [comment]
@PMehrfeld next try :)

**Pull request merged**
