### PR TITLE
Issue397 window models

### PR DESCRIPTION
**Pull request by mla-srs**
Integrated the window models based on VDI 6007 into the AixLib.

### CODE REVIEW

**Comment by mla-srs** [comment]
Thanks @PRemmen, did you revert my latest commit?

**Comment by PRemmen** [comment]
No I just did a merge with development, and then forced to push in this branch.

**Comment by mla-srs** [comment]
Ok thanks

**Comment by mla-srs** [comment]
Due to the git problems, I will open a new branch and new PR.

**Comment by PMehrfeld** [comment]
@mla-srs and @mlauster: since now a new branch on this issue exists, this old one should be deleted. Or is it still valuable? Additionally, a branch issue397_testMerge exists. If someone of you is sure that these branches can be deleted, this should be done in order to avoid left over branches in AixLib :)

**Comment by mlauster** [comment]
@PMehrfeld, yes, both should be deleted, thanks for catching that! I will leave it up to @mla-srs to delete them since he worked with both branches and maybe would like to keep them for some reasons.

**Pull request closed without merging**
