### PR TITLE
Issue149 communication package

### PR DESCRIPTION
**Pull request by GeorgFerdinandSchneider**
Ready for pull request, also see comment from last commit

### CODE REVIEW

**Comment by marcusfuchs** [comment]
@GeorgFerdinandSchneider Thank you for this contribution! I think this is a very useful enhancement. Before merging, there are nevertheless a few open points:

1. As explained in https://github.com/RWTH-EBC/AixLib/wiki/Structure-of-AixLib-Repository, we try to collect new additions in the `development` branch. Therefore, this PR should be changed to merge into `development`, not into the `master`
- A check of the models with `rununittests.py -- validate-html-only` (see https://github.com/RWTH-EBC/AixLib/wiki/Unit-Tests for more details) returns quite a lot of html warnings for the code. It would be great if we could change that to correct html documentation of the models. (The list of html warnings is attached below)
- usually, we keept our revision history in the models from most recent (on top) to oldest (at the bottom), in your models, it is the other way round
- In `AixLib.Utilities.Communication.SocketCommunication.UsersGuide.Contact`, your additions are summed up under the term "The Library". Would it be possible to change that to e.g. "The SocketCommunication package"? Otherwise there may be confusion whether "The Library" referes to the package or AixLib as a whole. Same goes for the licensing in `AixLib.Utilities.Communication.SocketCommunication.UsersGuide.Documentation.License`. Would it be sufficient to remove that, as the whole of AixLib is under Modelica 2.0 license?
- The package contains `AixLib.Utilities.Communication.SocketCommunication.UsersGuide.ReleaseNotes`, which is a bit problematic, as this will also be in conflict with AixLib as a whole and its versioning. Could we remove that? If it needs to stay, "Oktober" should be changed to "October". Also, we would need a strategy and someone responsible for managing this separate versioning within AixLib, which may be nearly impossible.
- Would it be possible to extend the documentation of `AixLib.Utilities.Communication.SocketCommunication.Examples.ExampleClientLoop` to include directions on how to run the example server? Without any background knowledge, I was not able to figure that out to run the example successfully. Also a minor thing: The documentation reads `The server simply returns what he received. `. I think `he` should be changed to `it.`
- In the documentation of `AixLib.Utilities.Communication.SocketCommunication.Components.TCPCommunicatorExample` it would be great to change the given url and code words to be hyperlinks and `<code>` elements for the user's convenience.
- `AixLib.Utilities.Communication.SocketCommunication.Components.Internal.TCPCommunicatorBasic` gives example code, that the user is asked to uncomment. Would it be possible to transfer that to an example model, so that the example is directly ready to run without the user having to change code?
- Finally, would it be possible (e.g. in the user's guide section) to give a practical example use case for this package, so that the user may directly see possible applications?

Sorry to have so many comments on your work. I would be willing to help, e.g. regarding the documentation style and html warnings. But I think it would be great to finish this work acording to the library's standards.

List of html warnings:
```
The following malformed html syntax has been found:
[-- .\Utilities\Communication\SocketCommunication\package.mo ]
line 17 column 39 - Warning: <br> element not empty or not closed
line 25 column 39 - Warning: <br> element not empty or not closed

[-- .\Utilities\Communication\SocketCommunication\Components\TCPCommunicatorE
ple.mo ]
line 17 column 39 - Warning: <br> element not empty or not closed
line 25 column 39 - Warning: <br> element not empty or not closed
line 31 column 39 - Warning: <br> element not empty or not closed
line 41 column 1 - Warning: trimming empty <p>
line 59 column 1 - Warning: trimming empty <p>
line 65 column 1 - Warning: trimming empty <p>

[-- .\Utilities\Communication\SocketCommunication\Examples\ExampleClientLoop.
]
line 17 column 39 - Warning: <br> element not empty or not closed
line 23 column 39 - Warning: <br> element not empty or not closed
line 129 column 41 - Warning: unescaped & or unknown entity "&wsaData"
line 141 column 16 - Warning: unescaped & or unknown entity "&hints"
line 155 column 47 - Warning: unescaped & or unknown entity "&hints"
line 155 column 55 - Warning: unescaped & or unknown entity "&result"
line 51 column 1 - Warning: trimming empty <p>

[-- .\Utilities\Communication\SocketCommunication\Functions\TCP\package.mo ]
line 19 column 1 - Warning: <br> element not empty or not closed

[-- .\Utilities\Communication\SocketCommunication\Functions\TCP\SocketDestruc
o ]
line 37 column 2 - Warning: trimming empty <p>
line 123 column 1 - Warning: trimming empty <p>

[-- .\Utilities\Communication\SocketCommunication\Functions\TCP\SocketReceive
 ]
line 33 column 2 - Warning: trimming empty <p>
line 109 column 1 - Warning: trimming empty <p>

[-- .\Utilities\Communication\SocketCommunication\Functions\TCP\SocketSend.mo
line 103 column 1 - Warning: trimming empty <p>

[-- .\Utilities\Communication\SocketCommunication\Functions\TCP\TCPConstructo
o ]
line 35 column 1 - Warning: trimming empty <p>
line 89 column 1 - Warning: trimming empty <p>

[-- .\Utilities\Communication\SocketCommunication\Functions\TCP\Internal\Sock
onnect.mo ]
line 97 column 37 - Warning: unescaped & or unknown entity "&gHints"
line 97 column 46 - Warning: unescaped & or unknown entity "&gpResult"

[-- .\Utilities\Communication\SocketCommunication\Functions\TCP\Internal\Sock
isconnect.mo ]
line 95 column 1 - Warning: trimming empty <p>

[-- .\Utilities\Communication\SocketCommunication\Functions\TCP\Internal\Sock
nit.mo ]
line 97 column 37 - Warning: unescaped & or unknown entity "&gWsaData"
line 109 column 17 - Warning: unescaped & or unknown entity "&gHints"
line 87 column 1 - Warning: missing </pre> before <h4>
line 124 column 14 - Warning: inserting implicit <pre>
line 126 column 2 - Warning: discarding unexpected </body>
line 127 column 2 - Warning: discarding unexpected </html>
line 124 column 14 - Warning: missing </pre>
line 31 column 1 - Warning: trimming empty <p>
line 85 column 1 - Warning: trimming empty <p>

[-- .\Utilities\Communication\SocketCommunication\UsersGuide\Contact.mo ]
line 25 column 29 - Warning: <br> element not empty or not closed
line 35 column 30 - Warning: <br> element not empty or not closed
line 37 column 46 - Warning: <br> element not empty or not closed
line 39 column 52 - Warning: <br> element not empty or not closed
line 41 column 37 - Warning: <br> element not empty or not closed
line 43 column 25 - Warning: <br> element not empty or not closed
line 45 column 31 - Warning: <br> element not empty or not closed
line 47 column 100 - Warning: <br> element not empty or not closed
line 53 column 23 - Warning: <br> element not empty or not closed
line 55 column 12 - Warning: <br> element not empty or not closed
line 57 column 27 - Warning: <br> element not empty or not closed
line 59 column 30 - Warning: <br> element not empty or not closed
line 61 column 80 - Warning: <br> element not empty or not closed
line 67 column 18 - Warning: <br> element not empty or not closed
line 69 column 27 - Warning: <br> element not empty or not closed
line 71 column 32 - Warning: <br> element not empty or not closed
line 73 column 63 - Warning: <br> element not empty or not closed
line 75 column 22 - Warning: <br> element not empty or not closed
line 77 column 28 - Warning: <br> element not empty or not closed
line 79 column 100 - Warning: <br> element not empty or not closed
line 29 column 1 - Warning: <table> lacks "summary" attribute
```

**Comment by GeorgFerdinandSchneider** [comment]
@marcusfuchs

Thanks for your comments and the feedback provided. Please find the answers to your comments according to the numbering above:

1.) Completely fine, please switch PR to development branch
2.) Done. Please recheck
3.) Done.
4.) First point is done. I removed the license entry. I am fine with the Modelica 2.0 license. Is this ok? @AnaConstantin
5.) The package should migrate to AixLib, I  deleted the release notes and changed naming and description in AixLib.Utilities.Communication.SocketCommunication.UsersGuide.Contact 
7.) Done.
9.) I added "ApplicationAreas" in the users guide where I reference a contribution to Modelica conference 2015 where an example application of the package is reported. Would this be sufficient?

6.) I think we will have to discuss this also with @AnaConstantin. Probably it is a possibility to include a compiled version of the server (*.exe). Though this might cause problems if people use the package on different platforms (currently it is only tested with Win7 and Dymola 2015)
8.) I will think about it and come back to you

**Comment by marcusfuchs** [comment]
@GeorgFerdinandSchneider 

I had a quick look found the following:
2.) This seems almost finished, the remaining html errors are
```
`The following malformed html syntax has been found:
[-- .\Utilities\Communication\SocketCommunication\Functions\TCP\I
onnect.mo ]
line 97 column 37 - Warning: unescaped & or unknown entity "&gHin
line 97 column 46 - Warning: unescaped & or unknown entity "&gpRe

[-- .\Utilities\Communication\SocketCommunication\Functions\TCP\I
isconnect.mo ]
line 95 column 1 - Warning: trimming empty <p>

[-- .\Utilities\Communication\SocketCommunication\UsersGuide\Cont
line 31 column 1 - Warning: <table> lacks "summary" attribute
```
5.) and 9.) It seems that the `ApplicationAreas` are mentioned in the `package.order` file, but is it possible that the file itself has not been committed yet? And the folder for the `ReleaseNotes` seems to be still present on the repo, this should be deleted.

Overall, this seems to be on track nicely, will be great when you have coordinated the remaining open points with @AnaConstantin.

**Comment by GeorgFerdinandSchneider** [comment]
Final check of example is passed and i corrected some more HTML documentation faults.

@marcusfuchs: probably you may give it another try with the example ?

 If everyone is OK I would propose to merge this branch into development.

**Comment by marcusfuchs** [comment]
@GeorgFerdinandSchneider and @AnaConstantin:
I tried to pull the latest changes from `GeorgFerdinandSchneider:issue149_communicationPackage` and from `AixLib:issue149_communicationPackage` into my local Repo for testing and I get some conflicts between these two branches. Could you merge these two branches and pull the latest `AixLib:development` into that merged branch, so that we can be sure to be free of conflicts for this?

I also had a look at the server example, and the documentation seems very well done and clear. When trying to run the `exampleserver.exe`, I get the error of a missing `MSVCR100D.dll` on my machine, though.

**Comment by mlauster** [comment]
is handled in #259

**Pull request closed without merging**
