### PR TITLE
WIP: Issue736 heat pump naming fix

### PR DESCRIPTION
**Pull request by Dawac**
Changed the enthalpy port names according to #736

### CODE REVIEW

**Comment by PMehrfeld** [comment]
@Dawac and @DaJansenGit : If I saw it correctly, there is a [conversion script](https://github.com/RWTH-EBC/AixLib/wiki/Conversion-Scripts) (and raise of version number) necessary. 
But be aware that with PR #723, which will be merged soon, also an increase in version number occurs.

**Comment by DaJansenGit** [comment]
> @Dawac and @DaJansenGit : If I saw it correctly, there is a [conversion script](https://github.com/RWTH-EBC/AixLib/wiki/Conversion-Scripts) (and raise of version number) necessary.
> But be aware that with PR #723, which will be merged soon, also an increase in version number occurs.

Thanks for your hint! Ok, then we will wait for #723, create a conversion script and merge afterwards.

**Comment by DaJansenGit** [comment]
@PMehrfeld 
I saw #723 was merged today. So I updated the branch, added the conversion script and raised the version number. Can you have a short look if everything is correct? It's my first conversion time :D

**Comment by PMehrfeld** [comment]
@DaJansenGit : Looks good!

Anyway, be aware that you somehow have the publications.md in your branch. The file is currently part of `master` but not `development`.
If you are using this branch to bring the file also into `development`, I am fine with it.

**Comment by DaJansenGit** [comment]
> @DaJansenGit : Looks good!
> 
> Anyway, be aware that you somehow have the publications.md in your branch. The file is currently part of `master` but not `development`.
> If you are using this branch to bring the file also into `development`, I am fine with it.

@Dawac Was this on purpose to include the publications.md? I'm fine with it too.

**Comment by Dawac** [comment]
@DaJansenGit It was actually not on purpose. Must have gotten into the branch somehow :D Thanks for the review and the conversion script!

**Pull request merged**
