### PR TITLE
issue149_communicationPackage Merge upstream

### PR DESCRIPTION
**Pull request by GeorgFerdinandSchneider**
Final check of ExampleClientLoop.mo passed successfully.

Need for some html documentation cleansing (<code></code>, <p></p>...)

### CODE REVIEW

**Comment by GeorgFerdinandSchneider** [comment]
created this for merging the two branches (GeorgFerdinandSchneider:issue149_communicationPackage and from AixLib:issue149_communicationPackage). 

conflicts will need to be resolved

**Comment by marcusfuchs** [comment]
@GeorgFerdinandSchneider @AnaConstantin :

This pull request states that "conflicts will need to be resolved". Do we have plan of action as to who will resolve these conflicts?

**Comment by AnaConstantin** [comment]
Yes, it will happen today, or by the end of the week.

**Comment by marcusfuchs** [comment]
I think there's no rush, just wanted to clarify whether this is on track or whether help is needed.

**Pull request merged**
