### PR TITLE
Issue276 building2thermalzones

### LINKED ISSUE #276: Integrate Building into ThermalZones
On the long run, we should incorporate our models for building physics, currently at home in `AixLib.Building`-package, into `AixLib.ThermalZones`-package to comply with `Annex60`-structure. 
For `AixLib.Building.LOM`, major parts are done in #260, this issue here is to collect and solve remaining parts of `AixLib.Building`:
- [x] Move `AixLib.Building.LowOrder.Validation.ASHRAE140` to `AixLib.ThermalZones.ReducedOrder.Validation.ASHRAE140`. For that, the test cases need to be modified to use `AixLib.ThermalZones.ReducedOrder` models and possibly `AixLib.BoundaryConditions` weather data handling
- [x] Move `AixLib.Building.HighOrder`. @AnaConstantin, can you estimate how much work that is and what has to be done for that?
- [x] File through `AixLib.Building.Components` and decide where they should find their new home. I suggest to:
  - [x] Move major parts (`AixLib.Building.Components.Walls`, `AixLib.Building.Components.WindowsDoors`,`AixLib.Building.Components.DryAir`) to `AixLib.ThermalZones.HighOrder` .
  - [x] Get rid of `AixLib.Building.Components.Weather` or integrate it in `AixLib.BoundaryConditions`.
  - [x] Find a new home for `AixLib.Building.Components.Sources`. They are used by `AixLib.Building.HighOrder` and `AixLib.Building.LowOrder`, one solution could be to integrate them in `AixLib.Building.HighOrder` or `AixLib.Utilities.Sources`.

### PR DESCRIPTION
**Pull request by mlauster**
This closes #276.
This PR finally moves `HighOrder` and `Components` from `Buildings` package, mainly to `ThermalZones.HighOrder`. `Weather` is moved to `BoundaryConditions.WeatherData.Old`, since it will be deprecated in some point in time, but currently too many people still rely on that model. `InternalGains` is moved to `Utilities`, since we have here already sources like `IdealHeaterCooler`.
This PR comes with a conversion script to modify existing dependent models. Since it is called if somebody is using AixLib in version 0.6.0, no matter to what the new version is, I kept 0.6.0 as the current version number. When we release the next version, we can easily switch to whatever version number we like. We only need to consider in-between releases and raise the number in the conversion script call in package.mo of AixLib. Otherwise, if somebody e.g. uses version 0.6.1, the conversion script won't be called.
I created a test file with all moved files here: https://gist.github.com/mlauster/79b5768e4909716ba826e77f82645e75
This can be used to test if the conversion script works. Just checkout the branch and load this file in Dymola. Afterwards, all icons of all models in the test file should be visible.

### CODE REVIEW

**Comment by mlauster** [comment]
The link to the gist file was corrupt, I corrected it:
https://gist.github.com/mlauster/79b5768e4909716ba826e77f82645e75

**Comment by PMehrfeld** [comment]
This closes #605 as well.

**Comment by PMehrfeld** [comment]
All commits are online now. 
Check of `AixLib.ThermalZones.HighOrder` did not through any error.

I suggest to merge this branch into the one related to #603. There, the version number is raised anyway. Thus, the new package structure and the bug fix would be in the release v0.6.1.

What do you think @mlauster ?

**Comment by mlauster** [comment]
@PMehrfeld, I agree with all your points. My plan is to merge this branch into development and create a new branch from development for #603 and merge this one back afterwards into development. Otherwise, we will be off-sync with master and development when we merge #306 directly into master. Do you agree to this plan?

**Comment by PMehrfeld** [comment]
I would slightly revise this plan, because otherwise we would have a development version 0.6.0 where the conversion script would not be executed, but with changed library structure. 
What about creating a branch `issue603_...`. Merge `issue276_building2thermalzones` directly into `issue603...`. Afterwards merge the bugfixed IBPSA repo into `issue603...` and then `issue603...` into `development` and then `development` into `master`. And finally do the release.

**Pull request merged**
