### PR TITLE
Improved model for heat convection of inside walls

### PR DESCRIPTION
**Pull request by PMehrfeld**
Added equations for calculation of alpha according to EN ISO 6946 and constant alpha. Adapted in Examples/HeatTransfer_test.mo

### CODE REVIEW

**Comment by mlauster** [comment]
@PMehrfeld: Did you clarify if these changes do not collide with the intentions of the pre-developers of the model? If so we can merge this.

**Comment by PMehrfeld** [comment]
@mlauster: Discussed with pre-developers. Ready to merge! Please check the change of multiplier "g" in the gain-model of the ASHRAE window.

**Comment by mlauster** [comment]
@PMehrfeld: Did you update the documentation?
Why did you need to change WindowType.g to g? Does this mean that one has to define g seperately to the WindowType record? Or is it computed beforehand on the basis of some values out of the record?

**Comment by PMehrfeld** [comment]
@mlauster: g is either a parameter of a record or a manually chosen constant value:
parameter Real g= if selectable then WindowType.g else 0.60 "Coefficient of solar energy transmission";
But if you chose your own g-value, it wouldn't be used in the Gain model.

**Comment by mlauster** [comment]
I couldn't find 
parameter Real g= if selectable then WindowType.g else 0.60 "Coefficient of solar energy transmission";
Does this mean, it is either the value in the record or 0.6? What is then about own values? Or is this just an example and my concern is fully taken care of at some part in the model? In this case, I'm  okay to merge. :-)

**Comment by PMehrfeld** [comment]
@mlauster: 0.6 is only the default value. Ready to merge.
this closes #83

**Pull request merged**
