### PR TITLE
replaces __Dymola_Images with groupImage

### LINKED ISSUE #328: Replace non-standard annotation by standard annotation attribute `groupImage`
There are plenty of `__Dymola_Images.Parameters.source` annotations in the models that can be substituted by the standard-conform (as of MLS 3.2) annotation attribute `groupImage`. See https://github.com/modelica/Modelica/issues/408 for the corresponding issue on the MSL.

### PR DESCRIPTION
**Pull request by mlauster**
This closes #328

@AnaConstantin, I hope I didn't break anything, all occurrences were in the HOMs. So far, I didn't get any new warnings and I couldn't see a difference in the models or parameter windows.

### CODE REVIEW

**Comment by tbeu** [comment]
I believe you need a Modelica URI, i.e., ``groupImage="modelica://AixLib/Resources`.

**Comment by mlauster** [comment]
@tbeu thanks, I did as you suggested. It seemed to work on my machine in any case, but is clearly the better way.

**Comment by tbeu** [comment]
Can you please attach a screen shot where you see such a groupImage in the dialog, say AixLib.Building.HighOrder.Rooms.OFD.Attic_Ro2Lf5.

Also, Dialog has neither Width nor Length annotations. Thus, they should be removed.

**Comment by mlauster** [comment]
Hm, you are right, this is the image that should be incorporated
target
This is how it looks like:
withmodelica
This is how it looked like befor making changes:
withdymola
So something seems to be wrong for a longer time.
@AnaConstantin, can you help out here?

**Comment by tbeu** [comment]
> So something seems to be wrong for a longer time.

Thanks for confirmation. I believe the annotation should be moved to the first relevant parameter. Check out how Modelica.Magnetic.FluxTubes.Examples.MovingCoilActuator.Components.PermeanceActuator does it.

**Comment by mlauster** [comment]
@tbeu, thanks, that works!  I moved `groupImage = "modelica://AixLib/Resources/Images/Building/HighOrder/Attic_2Ro_5Rooms.png"` from the model annotation to the first relevant parameter a got:
unbenanntes bild
We now have clashes with the text, I think @AnaConstantin needs to decide how she wants to handle it and if smaller graphics are sufficient

**Comment by mlauster** [comment]
The clash can be solved by adding the annotation to the critical parameter (Thermal Insulation Regulation in this case) instead of the first one. @AnaConstantin, would you like to have your graphics always in the dimensions group or above?

**Comment by tbeu** [comment]
Yes, @AnaConstantin is already set as reviewer.

**Comment by AnaConstantin** [comment]
Thank you @tbeu and @mlauster for the constructive discussion. I like the way the picture is represented and I think the fact that you have do add it to the "critical parameter", is not optimal, but on the other hand it gets the job done. We need to have a hint somewhere in wiki or in the documantetaion template about this. 
I do not consider it a problem that the picture beloings to another group, the idea was always to have the dimensions underneath the picture.

**Comment by mlauster** [comment]
Okay, I moved all anntoations, but image size is still an issue. @AnaConstantin, please check while reviewing and resize where appropriate.

**Comment by AnaConstantin** [comment]
@mlauster thanks a lot for the work done. I decided to resize three images. While I was in the packages I corrected three other mistakes, as explained in last commit (https://github.com/RWTH-EBC/AixLib/pull/369/commits/3a12f6d25d7de6549b6143f3d3d592dff838f8a3).
@tbeu thank you very much for your contribution.
If we ever make a tipps and tricks page, this "groupImage" annotation trick should be included.

**Pull request merged**
