### PR TITLE
Ci updates

### PR DESCRIPTION
**Pull request by FWuellhorst**
Updates with new CI scripts

### CODE REVIEW

**Comment by FWuellhorst** [comment]
@DaJansenGit This is ready for review, i fixed the naming-guideline path in ModelicaPyCI. For a review of functionality, you have to checkout the branch AixLibCI in templates and the PR in ModelicaPyCI.

**Review by FWuellhorst — COMMENTED** [review]
@DaJansenGit : Can you do your review now? The CI passes along with all regression tests :) I changed .mat to .txt to get them to work with latest buildingspy and fixed some wrong Modelica Syntax in HOM during debugging. Even though not the cause, I kept the fixes.

**Review by DaJansenGit — DISMISSED** [review]
The changes in CI look fine, the only thing that I'm wondering about is the changes in the ref results. My guess would be that these changes come from the new weather file formats. Maybe during the conversion there were some minimal numerical differences? The only model wise change that I see is the following code line and this was already set inside the validations models before

```
parameter Components.Types.selectorCoefficients absInnerWallSurf=AixLib.ThermalZones.HighOrder.Components.Types.selectorCoefficients.abs06
```

**Review by FWuellhorst — COMMENTED** [review]
I reverted the results, it works now. @DaJansenGit can you approve again?

**Review by DaJansenGit — APPROVED** [review]

**Pull request merged**
