### PR TITLE
Issue142 AHU conditional

### LINKED ISSUE #142: make AHU conditional
in MultizoneEquipped

### PR DESCRIPTION
**Pull request by mlauster**
This closes #142, #143

### CODE REVIEW

**Comment by mlauster** [comment]
@PMehrfeld, have a look at #142.

**Comment by mlauster** [comment]
Ok, looks fine!
I resolved some conflicts with development branch, @PMehrfeld please check if equation in line 188 in AHU.mo should be commented or not. In development, it was, in this branch not.
However, independent from this, we now get errors when checkung AHU.mo
@PMehrfeld, can you please take care of this? Please let me know if you need help.

**Comment by PMehrfeld** [comment]
@mlauster: Thanks a lot for checking. I have uncommented/commented the right/wrong lines.
I don't get error messages when checking AHU.mo or translating and simulating AHU example as well as MultizoneEquipped example (even in pedantic mode). Do you still receive errors?

**Comment by mlauster** [comment]
No, it's gone. So it was related to the merge conflict.
Ona last change: I deleted `editButton` from annotation of `AHU` as it is not standardized and gives a pedantic error.
@PMehrfeld, are you okay with that? I will merge then.

**Comment by PMehrfeld** [comment]
@mlauster: Please try as discussed with Dymola 2016 FD01. If the error still occurs in pedantic mode, go without `editButton`.

**Comment by mlauster** [comment]
unbenanntes bild

Sorry, I still get it. No idea why you don't get it.

**Comment by PMehrfeld** [comment]
OK, I have no idea why translation works at my computer but not at yours. Anyway, then please remove the annotation and merge the two branches :-) Thanks a lot.

**Comment by mlauster** [comment]
Marcus gets the same error, so we will leave that out.

**Pull request merged**
