### PR TITLE
Issue79 vdi

### PR DESCRIPTION
**Pull request by PRemmen**

### CODE REVIEW

**Comment by marcusfuchs** [comment]
It seems like the problems have been solved for the linear case, but for the star validaiton I get the error message:

Error: Scalar system is always singular for reducedModel.solarRadToHeatRad.port.T = (reducedModel.AbscoeffA.y*(1-reducedModel.solarRadToHeatRad.alpha*reducedModel.solarRadToHeatRad.T_ref))/( -reducedModel.AbscoeffA.y*reducedModel.solarRadToHeatRad.alpha) = 0/-0

Also, in order to discover possible problems with these models in the future, I added unit tests for the linear validation. I commited the unit tests to your branch, so please pull these chnages before continuing work on this branch. I will add further unit tests and process description to the wiki in the future.

**Comment by PRemmen** [comment]
okay I'll have a look at it later on

**Comment by PRemmen** [comment]
@marcusfuchs please check again! I added constraints for the windows in the partial model

**Comment by marcusfuchs** [comment]
Now all models run. I also added unit tests and reference results for the star validation.

**Pull request merged**
