### PR TITLE
Updated Publications.md

### PR DESCRIPTION
**Pull request by GeorgFerdinandSchneider**
Updated documentation with a publication on building automation systems which uses AixLib.

### CODE REVIEW

**Comment by GeorgFerdinandSchneider** [comment]
I suggest @PRemmen or @AnaConstantin as reviewers.

Best

**Comment by AnaConstantin** [comment]
@GeorgFerdinandSchneider thank you. Is this really building automation, or more of a specific application where the High order model from AixLib is used?

**Comment by GeorgFerdinandSchneider** [comment]
Sure @AnaConstantin should also be fine. How would you call this? May be "Applications and use ases"?

**Comment by AnaConstantin** [comment]
@GeorgFerdinandSchneider sorry for taking such a long time to answer. Yes: "Applications and Use Cases" sounds good. Can you please rename it?

**Comment by PMehrfeld** [comment]
This closes #831

**Comment by PMehrfeld** [comment]
I cannot change the source branch. Thus, I close this PR and open a new one.

**Pull request closed without merging**
