### PR TITLE
Issue365 level of development stars

### PR DESCRIPTION
**Pull request by FWuellhorst**
Reopening the pull request to see which files will cause a problem. This way i can fix the mistakes.

### CODE REVIEW

**Comment by FWuellhorst** [comment]
Fixed the errors shown by the Travis CI.
Should be ready to merge now.

**Comment by TobiasBlacha** [comment]
@FWuellhorst I think for some models the deletion of the stars is not enough. Sometimes the documentation refers to the stars, as for example: "4 stars because the model was validated with an AHU test bench at E.ON ERC EBC, RWTH Aachen University." in AixLib.Airflow.AirHandlingUnit.AHU.
We should also adjust the documentation in these cases.

**Comment by FWuellhorst** [comment]
Ok, i will think of a way to solve this with a script. Going through 210 files would be a lot of work.

**Comment by marcusfuchs** [comment]
Opening AixLib in Atom > right-click > `Search in Directory` > search for "stars" yields just the following two files for me:

- AixLib\Airflow\AirHandlingUnit\AHU.mo
- AixLib\DataBase\Surfaces\RoughnessForHT\PolynomialCoefficients_ASHRAEHandbook.mo

Of course you should double-check and you could script this, but I think it's neither necessary to do too much automation nor manual work on this.

**Comment by TobiasBlacha** [comment]
Yes you are right. So far I have seen it only in the aforementioned example. Perhaps it is the only model, I searched in the aixlib for the word "stars" and i have only received one hit.

**Comment by FWuellhorst** [comment]
In AixLib\DataBase\Surfaces\RoughnessForHT\PolynomialCoefficients_ASHRAEHandbook.mo the occurrence is in the revisions, should i delete it anyway? I will delete the line in  AixLib\Airflow\AirHandlingUnit\AHU.mo. If you now other models where an additional comment for the stars occur, i can delete them as well. Maybe there are some models where the additional comment is something like: "Because ..." without the word stars in it.

**Pull request merged**
