### PR TITLE
Resolves issue #207, corrects documentation for Machines/Machines_DIN…

### PR DESCRIPTION
**Pull request by AnaConstantin**
…18599.mo

### CODE REVIEW

**Comment by marcusfuchs** [comment]
@AnaConstantin 
The changes look good. Only the unit tests return the following html errors:

1. You changed `<br/>` to `<br>`. For the unit tests, it should be  the closed version `<br/>`.
2. In `AixLib/Building/Components/Sources/InternalGains/Machines/Machines_DIN18599.mo ` the table is missing a `summary` attribute.

**Comment by AnaConstantin** [comment]
@marcusfuchs Thank you!
I really need to learn to do this unit tests on my own, to better understand the report they provide. I'll get back to you on that. 
I'll have to see what a summary is for a table and see check into why dymola does funny things with html, but still displays the desired resulst.

**Comment by AnaConstantin** [comment]
Done, @marcusfuchs please redo unit tests when you have the time to see if the problems were solved.

**Comment by marcusfuchs** [comment]
Thanks @AnaConstantin , I just made very small last changes on docs format and will merge this.

**Pull request merged**
