### PR TITLE
Issue125 furtherLOModels

### PR DESCRIPTION
**Pull request by mlauster**
This adds various new models and fixes occuring bugs. Two things are still to do:
- New example crashes due to bad boundary conditions, define new ones
- Create new records for new example

I will handle this in a new branch.

### CODE REVIEW

**Comment by PRemmen** [comment]
Small docu for each model would be nice to have, to understand the differences between the models and make the right choice in combining the models

**Comment by mlauster** [comment]
I added documentation, changed icons, did some renaming and clean up. @PRemmen, can you please check again?

**Comment by PRemmen** [comment]
I checked the models and tried to simulate the examples. First time they run, once I change replacable models I get error messages. For example in ThermalZoneExample for changing buildingPhysics:

neue bitmap

For changing cor_g I get a mismatch of dimension.

**Comment by mlauster** [comment]
Okay, redeclaring should work now. See example for redeclaration syntax.

**Pull request merged**
