### PR TITLE
this fixes two missing links of parameters to the zoneBaseRecord, for…

### PR DESCRIPTION
**Pull request by mlauster**
… winterReduction and T0all for EMI in ventilationController

#136

### CODE REVIEW

**Comment by marcusfuchs** [comment]
As this is a bugfix for the master, this will bump us up to v0.2.1. Therefore, before accepting, could you please adjust the version in the top-level `package.mo` to `0.2.1` accordingly (seems like we forgot that for v0.2.0, therefore it still is listed as `0.1.0`)? After merging to the master, we should also transfer that to development.

**Comment by mlauster** [comment]
You are right, I forgot the new workflow. I will change the version number.

**Comment by PRemmen** [comment]
Example runs, so once the Versionnumber is changed, I can merge this.

**Comment by mlauster** [comment]
Okay, done.

**Pull request merged**
