### PR TITLE
Issue335 pipe models

### PR DESCRIPTION
**Pull request by TobiasBlacha**
This Pull Request refers to the issue #335

### CODE REVIEW

**Comment by TobiasBlacha** [comment]
@RoozbehSangi Thank you for your review and your comments, i will change this points.

**Comment by TobiasBlacha** [comment]
@RoozbehSangi  do you have a suggestion for the model name?

**Comment by RoozbehSangi** [comment]
Since it’s a general model that can be used for all cases, I would suggest the name “Pipe”. There is no models with this name either in AixLib or the Modelica Standard Library.

**Comment by TobiasBlacha** [comment]
@RoozbehSangi I have edited your change suggestions.

**Pull request merged**
