### PR TITLE
This fixes bug in indoor temperature in example by:

### PR DESCRIPTION
**Pull request by mlauster**
- Changing the calculation of the ventilation flow per zone. There were two mistakes:
  - The flow was weighted by the floor area and not by the required volume flow
  - conversion from m3/s to 1/h was done by multiplying the entire flow with the ground floor area of the entire building instead of the supplied zones areas
  Both things are now done by a new model called AirFlowRateSplit.mo. This lead to changes in SumCondition.mo to get in addition the share of volume flow per zone.
#168

### CODE REVIEW

**Comment by mlauster** [comment]
This will close #168

**Comment by PRemmen** [comment]
Building.LowOrder.Examples.MultizoneExample does not run. Error message:

```
ERROR: Failed to solve non-linear system using Newton solver.
To get more information: Turn on Simulation/Setup/Debug/Nonlinear solver diagnostics/Details
Solution to systems of equations not found at time = 2.98726E+007
   Nonlinear system of equations number = 3
   Infinity-norm of residue = 3.16057E+024
   Number of calls to nonlinear solver DymNL has reached or exceeded
   the maximum allowed number of function calls= 800
   Accumulated number of residue       calc.: 10753740
   Accumulated number of symbolic Jacobian calc.: 3132767
   Last values of solution vector:
multizoneEquipped.zone[3].machines_SensibleHeat_DIN18599.RadiativeHeat.port.T = -3.9029
multizoneEquipped.zone[3].lights.RadiativeHeat.port.T = -325.386
multizoneEquipped.zone[3].buildingPhysics.reducedOrderModel.outerwall.port_b.T = 281.482
multizoneEquipped.zone[3].buildingPhysics.reducedOrderModel.heatConvInnerwall.port_b.T = 275.742
multizoneEquipped.zone[3].internalGainsRad.T = -0.272958
multizoneEquipped.zone[3].buildingPhysics.reducedOrderModel.solarRadToHeatRad.port.T = 48.9847
multizoneEquipped.zone[3].human_SensibleHeat_VDI2078.RadiationConvertor.Therm.T = 6.14068E+007
   Last values of residual vector:
{ -0.050351, 0.124952, -1.58029E+024, 74.9268, -1.58029E+024,
  -496.997, -2.07351 }
 ```

Not exactly sure, where this is comming from, because as far as I see this zone is not supplied by the central AHU at all...

**Comment by PRemmen** [comment]
Runs not in Dymola 2016 but in 2016 FD01 since we focus on newest version this is okay.

**Comment by PMehrfeld** [comment]
Bug with indoor temperature is solved. Some further development regarding AHU air flow supply will be conducted in another branch.

**Pull request merged**
