### PR TITLE
issue264_Annex60_HP_review

### PR DESCRIPTION
**Pull request by PMehrfeld**
see #264

### CODE REVIEW

**Comment by marcusfuchs** [comment]
@PMehrfeld 
This PR seems to reintroduce an `HVAC` package, while this is no longer supposed to be part of AixLib. Do we need e.g. `AixLib/HVAC/HeatGeneration/HeatPump.mo` ? It is not loaded with the library in any case.

Also, many models' documentation still includes references to the old `HVAC`:
```
<p><h4><font color=\"#008000\">Level of Development</font></h4></p>
<p><img src=\"modelica://HVAC/Images/stars2.png\"/></p>
```
I think it would be best to simply remove these lines instead of updating the image reference.

**Comment by PMehrfeld** [comment]
@marcusfuchs : Folder `AixLib\HVAC\...` was from old Annex60_HP_review branch. I only deleted it from the library in Dymola. 
I also revised the documentations with the old image references.

**Comment by marcusfuchs** [comment]
@PMehrfeld 
Model looks great, last things that I found:

1. `AixLib.Fluid.HeatPumps.Examples.HeatPumpSimple` is broken. In #134 I had already replaced the static pipes with fixed resistances, but this change seems to be lost in the current version. Do we need this model? If yes, we could possibly checkout the file from #134, otherwise we could also just remove it.
2. `AixLib.Fluid.HeatPumps.Examples.HeatPumpDetailed` and `AixLib.Fluid.HeatPumps.Examples.HeatPumpDetailed_compare` seem to include the same models. Could we remove one of them?
3. `AixLib.Fluid.HeatPumps.Examples.HeatPumpDetailed_compare` and `AixLib.Fluid.HeatPumps.Examples.HeatPumpSimple_compare` should not include a `_` according to the style guide. If we decide to remove the other examples, these could simple be called `AixLib.Fluid.HeatPumps.Examples.HeatPumpSimple`, otherwise e.g. `AixLib.Fluid.HeatPumps.Examples.HeatPumpSimpleCompare` would be ok.
4. Many components and variables do not have a description string. Do we want to fix that in this PR or in a separate issue?

**Comment by PMehrfeld** [comment]
@marcusfuchs : Firstly, I have deleted examples that did not have the suffix "_compare", since these have been the older examples. Secondly, I have renamed the examples with "_compare" to `HeatPumpSimple` and `HeatPumpDetailed`. Furthermore, I enhanced the documentation of the detailed example saying that this model has more potential but left the default parametrization to keep the comparison between the two models.

Regarding issue 4.: I would suggest to open a new issue, since the task for Hackday was to transfer HVAC models to AixLib without being too rigorous. We can then be pedantic in the new issue. The second thought addresses also @AnaConstantin . Ana wants to enhance this heat pump model. So in a new issue she should express her intentions and then we should ensure better and more complete description strings.

**Comment by marcusfuchs** [comment]
Perfect, then I'll merge

**Pull request merged**
