### PR TITLE
Add scripts, rename, remove old files #1128

### LINKED ISSUE #1128: Refactor confusing names of heat pump safety models
The current heat pump controllers have two OnOff models: One to control the compressor, one that decides if operation is safe. 

Refactoring to avoid confusing is necessary. Any ideas for different names?

Affected models:
- `AixLib.Controls.HeatPump.BaseClasses.OnOffHP`
- `AixLib.Controls.HeatPump.HPControllerOnOff`
- `AixLib.Controls.HeatPump.SafetyControls.OnOffControl`

### PR DESCRIPTION
**Pull request by FWuellhorst**
Closes #1128

### CODE REVIEW

**Comment by FWuellhorst** [comment]
@katharinabr : Could you check this PR any time soon? :)

**Comment by FelixStege** [comment]
@FWuellhorst, @katharinabr, what's the status on this?

**Comment by FWuellhorst** [comment]
@FelixStege : I think Katharina won't be doing the review anymore. I think we should wait until the IBPSA heat pump merge is ready, as this will influence this PR.

**Comment by FWuellhorst** [comment]
Moved change to #1532

**Pull request closed without merging**
